//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class call
    {
        public int id { get; set; }
        public string calledNumber { get; set; }
        public System.TimeSpan callDuration { get; set; }
        public bool callType { get; set; }
        public int telephone_id { get; set; }
        public string comment { get; set; }
        public System.DateTime callDate { get; set; }
    
        public virtual number number { get; set; }
        public virtual telephone telephone { get; set; }
    }
}
