//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class manageCallsEntities2 : DbContext
    {
        public manageCallsEntities2()
            : base("name=manageCallsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<call> calls { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<number> numbers { get; set; }
        public virtual DbSet<roleInUnit> roleInUnits { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<telephone> telephones { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<view_rawReports> view_rawReports { get; set; }
        public virtual DbSet<view_roleAndUnit> view_roleAndUnit { get; set; }

        public System.Data.Entity.DbSet<WebApplication.Models.Login> Logins { get; set; }
    }
}
