//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleInUnit
    {
        public int id { get; set; }
        public System.DateTime createDate { get; set; }
        public int role_id { get; set; }
        public int unit_id { get; set; }
        public int user_id { get; set; }
    
        public virtual role role { get; set; }
        public virtual unit unit { get; set; }
        public virtual user user { get; set; }
    }
}
