//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_roleAndUnit
    {
        public string roleName { get; set; }
        public int unitID { get; set; }
        public string unitName { get; set; }
        public int id { get; set; }
        public int createDate { get; set; }
        public int role_id { get; set; }
        public int unit_id { get; set; }
        public int user_id { get; set; }
    }
}
