//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_rawReports
    {
        public string name { get; set; }
        public string familyName { get; set; }
        public string number { get; set; }
        public bool active { get; set; }
        public string unitName { get; set; }
        public string roleName { get; set; }
        public string comment { get; set; }
        public bool callType { get; set; }
        public string calledNumber { get; set; }
        public System.TimeSpan callDuration { get; set; }
        public System.DateTime callDate { get; set; }
        public int id { get; set; }
    }
}
